name: GIL vs Go Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.x'
    
    - name: Install bc
      run: sudo apt-get update && sudo apt-get install -y bc
    
    - name: Make script executable
      run: chmod +x run_comparison.sh
    
    - name: Run benchmark
      run: ./run_comparison.sh