name: Go Threading Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go-benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.x'
    
    - name: Install bc
      run: sudo apt-get update && sudo apt-get install -y bc
    
    - name: Make script executable
      run: chmod +x run_go.sh
    
    - name: Run Go benchmark
      run: ./run_go.sh