name: Python Threading Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install bc
      run: sudo apt-get update && sudo apt-get install -y bc
    
    - name: Make script executable
      run: chmod +x run_python.sh
    
    - name: Run Python benchmark
      run: ./run_python.sh